[default.fastbase]
openapi_url = ''
prefix = 'v1'

[default.fastbase_uvicorn]
host = "0.0.0.0"
port = 8000

[default.fastbase_db]
host = "localhost"
port = "5432"
username = "postgres"
password = "postgres"
name = 'postgres'
