[default.fase]
docs_url = '/docs'

[default.uvicorn]
host = "0.0.0.0"
port = 8000

[default.db]
type = "postgres"
host = "localhost"
port = "5432"
username = "postgres"
password = "postgres"
name = 'postgres'


[default.cors]
allow_origins = ['*']
allow_methods = ['*']
allow_headers = ['*']
