[default.fase]
docs_url = '/docs'
prefix = 'v1'

[default.uvicorn]
host = "0.0.0.0"
port = 8000

[default.db]
type = "postgres"
host = "localhost"
port = "5432"
username = "postgres"
password = "postgres"
name = 'postgres'
